apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todomvc-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<your-github-org-or-user>/capstone_kakali_playwright_todomvc'
    targetRevision: main
    path: charts/todomvc
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: todomvc-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
