apiVersion: apps/v1
kind: Deployment
metadata:
  name: todomvc-deployment
  namespace: demo-todomvc
  labels:
    app: todomvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todomvc
  template:
    metadata:
      labels:
        app: todomvc
    spec:
      containers:
      - name: todomvc
        image: kakalik/todomvc-app:1.0        
        ports:
        - containerPort: 9323
---
apiVersion: v1
kind: Service
metadata:
  name: todomvc
  namespace: demo-todomvc
spec:
  selector:
    app: todomvc # select pods with label app=todomvc
  type: NodePort
  ports:
    - protocol: TCP
      port: 9323 # port theat service will listen on
      targetPort: 9323 # port on the target pod (todomvc container)
      nodePort: 30003
  
